name: Test

on:
  delete

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "${{ github.event.ref }} - ${{ github.event.ref_type }}"
      - name: echo ref_name
        run: echo "${{ github.ref_name }}"
      - name: echo ref
        run: echo "${{ github.ref }}"
      - name: echo event ref_name
        run: echo "${{ github.event.ref_name }}"
      - name: echo env ref_name
        run: echo "$GITHUB_REF_NAME"
